### PR TITLE
Adding scroll functionality  and two more examples

### PR DESCRIPTION
**Pull request by vitormhenrique**
Hello.

I ported the library to micropython and I'm adding few functionalities, I'm keeping the circuitpython up to date. Added the scroll functionality and added two more examples.

### CODE REVIEW

**Comment by makermelissa** [comment]
Hi and thanks for working on this. I currently have a pull request in process with Adafruit and will review this after the pull request has been approved so I can make sure this doesn't vary too much.

**Comment by vitormhenrique** [comment]
No problem, I just added enabling the Graphic Cursor on my branch, after you analyze this if I need to do some changes I'll do at once and push the other functionalities as well.

**Comment by vitormhenrique** [comment]
Something that you might want to investigate, I could not figure it out yet, is how to get some characters printed on the screen....
writing ' \n'  for example does not make a new line even in text mode....

**Comment by makermelissa** [comment]
I think you'll need to use txt_set_cursor() to move the cursor. I believe it is the same way in the arduino library.

**Comment by vitormhenrique** [comment]
For the adafruit standard library yes, but on this one https://github.com/sumotoy/RA8875 the display is a subclass of stream, so it accepts println.

**Comment by makermelissa** [comment]
Yeah, it was originally designed around the Adafruit library since it was for Adafruit. I did make some enhancements based on the sumotoy library such as automatic mode switching though. However, if you would like to modify it to work with a newline character, that would be awesome.

**Comment by makermelissa** [comment]
Ok, now that my PR has been merged, I can get back to this. I integrated Travis CI with mu github to make it a bit easier for you. Could you go through and fix the issues and push again? They all look pretty simple pylint whitespace issues. Thanks.

**Comment by makermelissa** [comment]
Closing because this should really be PRed to Adafruit instead of this fork.

**Pull request closed without merging**
